#!/bin/bash

## Open folders
FILE="$HOME/.cache/eww_launch.dashboard"
CFG="$HOME/.config/eww/dashboard"
EWW=`which eww`
FM=dolphin

close_dash() {
	${EWW} --config "$CFG" close \
					background profile system clock uptime music github \
					reddit twitter youtube weather apps mail logout sleep reboot poweroff folders
	rm -rf "$FILE"
}

if [[ "$1" == "--dl" ]]; then
	close_dash && $FM ~/Downloads &

elif [[ "$1" == "--docs" ]]; then
	close_dash && $FM ~/Documents &

elif [[ "$1" == "--music" ]]; then
	close_dash && $FM ~/Music &

elif [[ "$1" == "--pics" ]]; then
	close_dash && $FM ~/Pictures &

elif [[ "$1" == "--cfg" ]]; then
	close_dash && $FM ~/.config &

elif [[ "$1" == "--local" ]]; then
	close_dash && $FM ~/.local/share &

fi
